import { supportedThemes } from '../recommendations.ts'

export const colourNames: Record<string, string> = {
  W: 'White',
  U: 'Blue',
  B: 'Black',
  R: 'Red',
  G: 'Green',
}
export const colourThemes: Record<string, [string, string]> = {
  W: ['#9b772e', '#f3df9b'],
  U: ['#286da8', '#8dc9ee'],
  B: ['#67506f', '#bf9ac8'],
  R: ['#a83b32', '#ee8b68'],
  G: ['#32734c', '#8bc795'],
  C: ['#666879', '#b8bac7'],
}

export const themeCommanders: Record<string, string[]> = {
  Tokens: [
    'Chatterfang, Squirrel General',
    'Rhys the Redeemed',
    'Jetmir, Nexus of Revels',
    'Baylen, the Haymaker',
    'Adrix and Nev, Twincasters',
    'Krenko, Mob Boss',
  ],
  '+1/+1 counters': [
    "Atraxa, Praetors' Voice",
    'Shalai and Hallar',
    'Hamza, Guardian of Arashin',
    'Sovereign Okinec Ahau',
    'Ezuri, Claw of Progress',
    'Felisa, Fang of Silverquill',
  ],
  Enchantments: [
    'Anikthea, Hand of Erebos',
    "Sythis, Harvest's Hand",
    'Tom Bombadil',
    "Go-Shintai of Life's Origin",
    'Ellivere of the Wild Court',
    'Zur the Enchanter',
  ],
  Graveyard: [
    'Meren of Clan Nel Toth',
    'Muldrotha, the Gravetide',
    'The Gitrog Monster',
    'Karador, Ghost Chieftain',
    'Chainer, Nightmare Adept',
    'Sidisi, Brood Tyrant',
  ],
  Dragons: [
    'The Ur-Dragon',
    'Miirym, Sentinel Wyrm',
    'Tiamat',
    'Lathliss, Dragon Queen',
    'Rivaz of the Claw',
    'Atarka, World Render',
  ],
  Spellslinger: [
    'Veyran, Voice of Duality',
    'Kess, Dissident Mage',
    'Niv-Mizzet, Parun',
    'Mizzix of the Izmagnus',
    "Kykar, Wind's Fury",
    'Stella Lee, Wild Card',
  ],
  Artifacts: [
    'Urza, Lord High Artificer',
    'Breya, Etherium Shaper',
    'Chiss-Goria, Forge Tyrant',
    'Osgir, the Reconstructor',
    'Shorikai, Genesis Engine',
    'Jhoira, Weatherlight Captain',
  ],
  Lifegain: [
    'Lathiel, the Bounteous Dawn',
    'Oloro, Ageless Ascetic',
    'Karlov of the Ghost Council',
    'Willowdusk, Essence Seer',
    'Heliod, Sun-Crowned',
    'Amalia Benavides Aguirre',
  ],
  Sacrifice: [
    'Korvold, Fae-Cursed King',
    'Meren of Clan Nel Toth',
    'Teysa Karlov',
    'Mazirek, Kraul Death Priest',
    'Juri, Master of the Revue',
    'Braids, Arisen Nightmare',
  ],
  Equipment: [
    'Syr Gwyn, Hero of Ashvale',
    'Wyleth, Soul of Steel',
    'Kellan, the Fae-Blooded',
    'Ardenn, Intrepid Archaeologist',
    'Akiri, Fearless Voyager',
    'Nahiri, Forged in Fury',
  ],
  'Group hug': [
    'Kynaios and Tiro of Meletis',
    'Gluntch, the Bestower',
    'Kwain, Itinerant Meddler',
    'Ms. Bumbleflower',
    'Phelddagrif',
    'Kenrith, the Returned King',
  ],
  Landfall: [
    'The Gitrog Monster',
    'Omnath, Locus of Creation',
    'Aesi, Tyrant of Gyre Strait',
    'Obuun, Mul Daya Ancestor',
    'Lord Windgrace',
    'Tatyova, Benthic Druid',
  ],
  Voltron: [
    "Light-Paws, Emperor's Voice",
    'Uril, the Miststalker',
    'Galea, Kindler of Hope',
    'Rafiq of the Many',
    'Slicer, Hired Muscle',
    'Wilson, Refined Grizzly',
  ],
  Goad: [
    'Marisi, Breaker of the Coil',
    'Kardur, Doomscourge',
    'Baeloth Barrityl, Entertainer',
    'Nelly Borca, Impulsive Accuser',
    'Firkraag, Cunning Instigator',
    'The Rani',
  ],
  'Big mana': [
    'Zhulodok, Void Gorger',
    'Goreclaw, Terror of Qal Sisma',
    'Kozilek, the Great Distortion',
    'Klauth, Unrivaled Ancient',
    'Imoti, Celebrant of Bounty',
    'Selvala, Heart of the Wilds',
  ],
  Blink: [
    'Brago, King Eternal',
    'Roon of the Hidden Realm',
    "Abdel Adrian, Gorion's Ward",
    'Preston, the Vanisher',
    'Yorion, Sky Nomad',
    'Aminatou, the Fateshifter',
  ],
  ETB: [
    'Yarok, the Desecrated',
    'Elesh Norn, Mother of Machines',
    'Chulane, Teller of Tales',
    'Roon of the Hidden Realm',
    'Preston, the Vanisher',
    "Abdel Adrian, Gorion's Ward",
  ],
  'Death triggers': [
    'Teysa Karlov',
    'Elas il-Kor, Sadistic Pilgrim',
    'Athreos, God of Passage',
    'Meren of Clan Nel Toth',
    'Liesa, Forgotten Archangel',
    'Kokusho, the Evening Star',
  ],
  Wither: [
    'The Scorpion God',
    'Hapatra, Vizier of Poisons',
    'Massacre Girl, Known Killer',
    'Yawgmoth, Thran Physician',
    'Volrath, the Shapestealer',
    'Grismold, the Dreadsower',
  ],
  Political: [
    'Queen Marchesa',
    'Breena, the Demagogue',
    'Kenrith, the Returned King',
    'The Council of Four',
    'Pramikon, Sky Rampart',
    'Xantcha, Sleeper Agent',
  ],
  Vampires: [
    'Edgar Markov',
    'Clavileño, First of the Blessed',
    'Strefan, Maurer Progenitor',
    'Carmen, Cruel Skymarcher',
    'Elenda, the Dusk Rose',
    'Olivia, Crimson Bride',
  ],
  Angels: [
    'Giada, Font of Hope',
    'Kaalia of the Vast',
    'Liesa, Shroud of Dusk',
    'Shalai and Hallar',
    'Aurelia, the Warleader',
    'Sigarda, Font of Blessings',
  ],
  Demons: [
    "Be'lakor, the Dark Master",
    'Rakdos, Lord of Riots',
    "K'rrik, Son of Yawgmoth",
    'Raphael, Fiendish Savior',
    'Vilis, Broker of Blood',
    'Beledros Witherbloom',
  ],
  Faeries: [
    'Alela, Cunning Conqueror',
    'Tegwyll, Duke of Splendor',
    'Obyra, Dreaming Duelist',
    'Talion, the Kindly Lord',
    'Alela, Artful Provocateur',
    "Nymris, Oona's Trickster",
  ],
  Vehicles: [
    'Shorikai, Genesis Engine',
    'Kotori, Pilot Prodigy',
    'Sydri, Galvanic Genius',
    'Depala, Pilot Exemplar',
    'Greasefang, Okiba Boss',
    'Magda, Brazen Outlaw',
  ],
  Indestructible: [
    'Karametra, God of Harvests',
    'Avacyn, Angel of Hope',
    'Zurgo Helmsmasher',
    'Toski, Bearer of Secrets',
    'Hazoret the Fervent',
    'Mogis, God of Slaughter',
  ],
  Mill: [
    'The Wise Mothman',
    "Captain N'ghathrod",
    'Phenax, God of Deception',
    'Bruvac the Grandiloquent',
    'Zellix, Sanity Flayer',
    'Anowon, the Ruin Thief',
  ],
  'Dual commanders': [
    'Thrasios & Tymna',
    'Kraum & Tymna',
    'Malcolm & Breeches',
    'Akiri & Silas Renn',
    'Ishai & Jeska',
    'Kodama & Sakashima',
  ],
  Zombies: [
    'Wilhelt, the Rotcleaver',
    'The Scarab God',
    'Varina, Lich Queen',
    'Gisa and Geralf',
    'Sidisi, Brood Tyrant',
    "Temmet, Naktamun's Will",
  ],
  Elves: [
    'Lathril, Blade of the Elves',
    'Marwyn, the Nurturer',
    'Ezuri, Renegade Leader',
    'Abomination of Llanowar',
    'Galadriel, Light of Valinor',
    'Tyvar the Bellicose',
  ],
  Goblins: [
    'Krenko, Mob Boss',
    'Muxus, Goblin Grandee',
    'Wort, Boggart Auntie',
    'Krenko, Tin Street Kingpin',
    'Shattergang Brothers',
    'Moria Marauder',
  ],
  Dinosaurs: [
    'Pantlaza, Sun-Favored',
    "Gishath, Sun's Avatar",
    'Atla Palani, Nest Tender',
    'Indoraptor, the Perfect Hybrid',
    'Owen Grady, Raptor Trainer',
    'Wayta, Trainer Prodigy',
  ],
  Merfolk: [
    'Hakbal of the Surging Soul',
    'Kumena, Tyrant of Orazca',
    'Emperor Mihail II',
    'Svyelun of Sea and Sky',
    'Tishana, Voice of Thunder',
    'Prime Speaker Zegana',
  ],
  Knights: [
    'Sidar Jabari of Zhalfir',
    'Syr Gwyn, Hero of Ashvale',
    'Éowyn, Shieldmaiden',
    'Aryel, Knight of Windgrace',
    'Wintermoor Commander',
    'Elenda and Azor',
  ],
  Spirits: [
    'Millicent, Restless Revenant',
    "Kykar, Wind's Fury",
    'Shilgengar, Sire of Famine',
    'Katilda, Dawnhart Martyr',
    'O-Kagachi, Vengeful Kami',
    'King of the Oathbreakers',
  ],
  Slivers: [
    'The First Sliver',
    'Sliver Overlord',
    'Sliver Gravemother',
    'Sliver Legion',
    'Morophon, the Boundless',
    'Sliver Hivelord',
  ],
}

export const dualCommanders: Record<string, string[]> = {
  'Thrasios & Tymna': ['Thrasios, Triton Hero', 'Tymna the Weaver'],
  'Kraum & Tymna': ["Kraum, Ludevic's Opus", 'Tymna the Weaver'],
  'Malcolm & Breeches': ['Malcolm, Keen-Eyed Navigator', 'Breeches, Brazen Plunderer'],
  'Akiri & Silas Renn': ['Akiri, Line-Slinger', 'Silas Renn, Seeker Adept'],
  'Ishai & Jeska': ['Ishai, Ojutai Dragonspeaker', 'Jeska, Thrice Reborn'],
  'Kodama & Sakashima': ['Kodama of the East Tree', 'Sakashima of a Thousand Faces'],
}
export const commanderNames = (name: string) => dualCommanders[name] ?? [name]
export const deckColumnSections = [
  ['Commander', 'Planeswalkers', 'Creatures'],
  ['Enchantments', 'Artifacts', 'Other Permanents'],
  ['Sorceries', 'Instants', 'Other Non-permanents'],
  ['Other', 'Lands'],
] as const
export const defaultCommanders = Object.values(themeCommanders).flat()
export const selectableThemes = Object.keys(themeCommanders).filter((name) =>
  supportedThemes.includes(name),
)
export const randomItems = <T>(items: T[], count: number) =>
  [...items].sort(() => Math.random() - 0.5).slice(0, count)
export const randomThree = (items: string[]) => randomItems(items, 3)
export const themeSearchTerms: Record<string, string> = {
  Tokens: 'o:token',
  '+1/+1 counters': 'o:"+1/+1 counter"',
  Enchantments: 'o:enchantment',
  Graveyard: 'o:graveyard',
  Dragons: 't:dragon',
  Spellslinger: 'o:"instant" o:"sorcery"',
  Artifacts: 'o:artifact',
  Lifegain: 'o:"gain life"',
  Sacrifice: 'o:sacrifice',
  Equipment: 'o:equipment',
  Landfall: 'o:landfall',
  Voltron: 'o:"commander you control"',
  Goad: 'o:goad',
  'Big mana': 'o:"add {"',
  Blink: 'o:"exile" o:"return"',
  ETB: 'o:"enters the battlefield"',
  'Death triggers': 'o:"dies"',
  Political: 'o:"each player"',
}
